{"name": "test_div[正数除以负数]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.33 == -0.33\n  +0.33\n  --0.33", "trace": "self = <testcode.test_calc_new.Test_Calculator object at 0x000001B30DF9A5E0>\nget_calc = <pythoncode.Calculator.Calculator object at 0x000001B30DF53190>, get_div_datas = [-1, -3, -0.33]\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_div_datas):\n        res = None\n        try:\n            res = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(res, float):\n                res = round(res, 2)\n            print(f'计算结果为：{res}')\n        except Exception as e:\n            print(e)\n>       assert res == get_div_datas[2]\nE       assert 0.33 == -0.33\nE         +0.33\nE         --0.33\n\ntest_calc_new.py:34: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "[-1, -3, -0.33]"}], "start": 1613319483972, "stop": 1613319483973, "uuid": "cf81e3c0-2fd9-41d1-84e4-9cc1003b30f2", "historyId": "db6f6da3038d53fcbb01b7f9f7e8c3da", "testCaseId": "c839c0b7efb7e833b1464aab293175a3", "fullName": "testcode.test_calc_new.Test_Calculator#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "parentSuite", "value": "testcode"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "Test_Calculator"}, {"name": "host", "value": "LAPTOP-K9V7IUFS"}, {"name": "thread", "value": "3596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcode.test_calc_new"}]}